name: test-self

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  ansible-collection:
    uses: ./.github/workflows/ansible-collection.yml
    with:
      platform: ubuntu-latest
      collection-path: tests/test_collection
      force_all_roles: true
