name: test-self

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  ansible-collection:
    uses: ./.github/workflows/ansible-collection.yml
    with:
      platform: ubuntu-latest
